version: "3"

networks:
  e-commerce:
    external: false

volumes:
  keycloak:
    driver: local
  # mongo:
  #   driver: local

services:
  server1:
    image: server
    build: ./server
    environment:
      - MONGO_URL=mongodb+srv://Nelson:ruqiulixia0220@chatsys.czvnacb.mongodb.net/?retryWrites=true&w=majority
    networks:
      - e-commerce
  server2:
    image: server
    environment:
      - MONGO_URL=mongodb+srv://Nelson:ruqiulixia0220@chatsys.czvnacb.mongodb.net/?retryWrites=true&w=majority
    networks:
      - e-commerce
  ui1:
    image: ui
    build: ./ui
    networks:
      - e-commerce
  ui2:
    image: ui
    depends_on:
      - ui1
    networks:
      - e-commerce
  load_balancer:
    image: nginx_load_balancer
    build: ./load-balancer
    networks:
      - e-commerce
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - ui1
      - ui2
      - server1
      - server2
  keycloak:
    image: keycloak18
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=keycloak
      # # NOTE: this is only for demonstration purposes
      # # ordinarily, you should NOT embed passwords in files
      - KEYCLOAK_PASSWORD=keycl0ak
    restart: always
    networks:
      - e-commerce
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    ports:
      - "127.0.0.1:8081:8080"
  e2e:
    image: e2e
    build: ./
    depends_on:
      - server1
    networks:
      - e-commerce

  # mongo:
  #   image: mongo:4
  #   container_name: mongo
  #   restart: always
  #   networks:
  #     - lecture21
  #   volumes:
  #     - mongo:/data/db
  #   ports:
  #     - "127.0.0.1:27017:27017"
